version: '3.9'

services:
  slim:
    image: slim:v1
    build: ./dockerfile/php
    container_name: slim
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./dockerfile/php/php.ini:/usr/local/etc/php/php.ini

networks:
  default:
    name: slim